version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn run semantic-release || true
